from typing import Any, Dict, Iterable, List


def weighted_portfolio_risk(
    selected_indices: Iterable[int],
    vendors_data: List[Dict[str, Any]],
) -> float:
    indices = list(selected_indices)

    total = sum(
        float(vendors_data[i].get("requested_amount", 0.0))
        for i in indices
    )

    if total <= 0:
        return 0.0

    return sum(
        float(vendors_data[i].get("predicted_risk", 0.0))
        * float(vendors_data[i].get("requested_amount", 0.0))
        for i in indices
    ) / total


def weighted_portfolio_return(
    selected_indices: Iterable[int],
    vendors_data: List[Dict[str, Any]],
) -> float:
    """Return the requested-capital-weighted expected return for a portfolio."""
    indices = list(selected_indices)

    total = sum(
        float(vendors_data[i].get("requested_amount", 0.0))
        for i in indices
    )

    if total <= 0:
        return 0.0

    return sum(
        float(vendors_data[i].get("expected_return", 0.0))
        * float(vendors_data[i].get("requested_amount", 0.0))
        for i in indices
    ) / total


def expected_portfolio_value(
    selected_indices: Iterable[int],
    vendors_data: List[Dict[str, Any]],
) -> float:
    """
    Expected monetary return generated by the selected portfolio.

    The value is scaled by 100,000 to keep the optimization objective
    numerically well-conditioned for QUBO/QAOA.

    Example:
        expected_return=0.16
        requested_amount=25,000

        contribution = 0.16 * 25,000 / 100,000
                      = 0.04
    """
    indices = list(selected_indices)

    return sum(
        float(vendors_data[i].get("expected_return", 0.0))
        * float(vendors_data[i].get("requested_amount", 0.0))
        / 100_000.0
        for i in indices
    )


def business_objective(
    selected_indices: Iterable[int],
    vendors_data: List[Dict[str, Any]],
) -> float:
    """
    Canonical optimization objective.

    Maximize expected monetary return from the capital allocated
    to the selected vendors.

    Risk, capital, and concentration are handled separately
    as hard portfolio constraints.
    """
    return expected_portfolio_value(selected_indices, vendors_data)